### ISSUE TITLE
Code of Conduct 404

### ISSUE THREAD

**Issue by 0x62** [slackhq/go-audit#2]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Link in CONTRIBUTING.md points to CODE_OF_CONDUCT.md within `.github`, however is actually located in project root. Should contributing docs be updated to point to correct location, or code file moved to `.github`?

**Comment by nbrownus** [comment]
Thanks! fixed by db01785
