### ISSUE TITLE
reopen govendor sync on rhel 6.5 just hangs 

### ISSUE THREAD

**Issue by jamiesonbc** [slackhq/go-audit#24]
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Now using the contrib spec file which means I need to complile on 6 to create the el6 rpm.
using a docker 6.5 container with golang 1.7 and govendor installed, when make executes govendor sync, it just hangs. Did same process on rhel 7.3 and does not hang

#### Reproducible in:

`go-audit` version: 752b3358719278e32d780677e9dde2b075a3c6d5OS version(s):

#### Steps to reproduce:

1. spectool -g -C ./rpmbuild go-audit.rpmbuild.spec
rpmbuild --define "_topdir %(pwd)/rpmbuild" \
        --define "_builddir %{_topdir}" \
        --define "_rpmdir %{_topdir}" \
        --define "_srcrpmdir %{_topdir}" \
        --define '_rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm' \
        --define "_specdir %{_topdir}" \
        --define "_sourcedir  %{_topdir}" \
        -ba go-audit.rpmbuild.spec2. 
3. 

### Expected result:

make completes

### Actual result:
make hangs at govendor

### Attachments:

> e.g. Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by nbrownus** [comment]
This is an issue between your environment and [govendor](https://github.com/kardianos/govendor), I encourage you to open an issue with them.

As a stop gap you can modify the `Makefile` to `go get` and `go build`.

**Comment by jamiesonbc** [comment]
I'm noticing that govendor is trying to clone a repository when it's hanging.
[root@lb274c go-audit-752b3358719278e32d780677e9dde2b075a3c6d5]# git clone https://gopkg.in/fsnotify.v1 /usr/lib/golang/.cache/govendor/gopkg.in/fsnotify.v1
Initialized empty Git repository in /usr/lib/golang/.cache/govendor/gopkg.in/fsnotify.v1/.git/

[strace.git.clone.txt](https://github.com/slackhq/go-audit/files/768059/strace.git.clone.txt)


When I run a similiar command for one of the other vendors in the vendor.json file .. it completes.

root@lb274c go-audit-752b3358719278e32d780677e9dde2b075a3c6d5]# git clone https://github.com/spf13/pflag /usr/lib/golang/.cache/govendor/github.com/spf13/pflag
Initialized empty Git repository in /usr/lib/golang/.cache/govendor/github.com/spf13/pflag/.git/
remote: Counting objects: 701, done.
remote: Total 701 (delta 0), reused 0 (delta 0), pack-reused 700
Receiving objects: 100% (701/701), 262.73 KiB, done.
Resolving deltas: 100% (454/454), done.
