### ISSUE TITLE
Viper issue has been fixed. Yay viper! 

### ISSUE THREAD

**Issue by andrewhowdencom** [slackhq/go-audit#27]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

The example yaml indicates that it's blocked by viper issue, that's since been resolved. Yay viper! 

#### Reproducible in:

Uhh here: https://github.com/slackhq/go-audit/blob/master/go-audit.yaml.example#L1-L5

#### Steps to reproduce:

Look above

### Expected result:

Nothing particularly. This is a heads up that it's been fixed.

### Actual result:

I filled out an awkward set of questions.

### Attachments:

Here's a cat! https://s-media-cache-ak0.pinimg.com/564x/45/91/b2/4591b2ec5726c7ad10537568415e8b07.jpg

**Comment by nbrownus** [comment]
Thanks! Updated the vendor file and removed the notice.
