### ISSUE TITLE
Doubled audit messages with journald

### ISSUE THREAD

**Issue by stephane-martin** [slackhq/go-audit#29]
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Hello, not really a go-audit issue, but there is some systemd behaviour that I think should be noticed: on recent versions of journald, journald by default listens to kernel audit messages by directly using a netlink socket.

That behaviour could generate double audit entries, or other strange issues, for example if you configure rsyslog to ingest journald messages, and also configure rsyslog to ingest go-audit messages.

To disable the journald audit socket:
`sudo systemctl mask systemd-journald-audit.socket`

Kind regards !

**Comment by nbrownus** [comment]
Thanks for reporting! I added it to the FAQ.
