### ISSUE TITLE
go-audit build issue

### ISSUE THREAD

**Issue by HLD** [slackhq/go-audit#32]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Build of go-audit not successful due to go path issues. 

Troubleshooting path issue, I attempted to use 'go get' but this failed with
error `177: undefined: user.LookupGroup`

#### Reproducible in:

`go-audit` version: 
OS version(s): CentOS 7

#### Steps to reproduce:

`$ go get github.com/slackhq/go-audit
`
```
pwd
/home/user/go/src/github.com/slackhq/go-audit
[user@localhost go-audit]$ make
govendor sync
go build
# github.com/slackhq/go-audit
./audit.go:177: undefined: user.LookupGroup
make: *** [bin] Error 2

```
### Actual result:

`./audit.go:177: undefined: user.LookupGroup
`

### Attachments:

> e.g. Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by nbrownus** [comment]
What version of `go` are you using?

**Comment by HLD** [comment]
The wrong version :) Thanks.
go version go1.6.3 linux/amd64
I've follwed the [digital ocean guide](https://www.digitalocean.com/community/tutorials/how-to-install-go-1-7-on-centos-7) to install 1.7 on CentOS 7, but I still see 1.6.3 when I run go version.

**Comment by nbrownus** [comment]
Pretty sure `user.LookupGroup` was introduced in v1.7 so you will need to upgrade to that before it will compile.

**Comment by HLD** [comment]
Appreciated. 
Go upgraded to 1.7, some flailing underway getting govendor to work.

**Comment by HLD** [comment]
Success. Thanks again @nbrownus 

- Not sure if this is specific to my setup, but I had to clone the go-audit project into my $GOPATH/src directory for it to build.
- Some issues getting govendor to work were helped with this [stackoverflow on govendor config ](https://stackoverflow.com/questions/42155805/govendor-dosnt-work-from-cmd)
