### ISSUE TITLE
Out of bound panic

### ISSUE THREAD

**Issue by stephane-martin** [slackhq/go-audit#37]
* [X ] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [ X] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [ X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Had once a panic in logs that came from an out of bound array in parser.go.

#### Reproducible in:

`go-audit` version: HEAD
OS version(s): Linux Ubuntu 16.04

#### Steps to reproduce:
??

**Comment by nbrownus** [comment]
Would you happen to have a stack trace?
