### ISSUE TITLE
Ship an official Docker image

### ISSUE THREAD

**Issue by yuvipanda** [slackhq/go-audit#39]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/mx,ster/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Ship an official Docker image for go-auditd. Should be as simple as adding a Dockerfile here and setting up automated builds on DockerHub.  Would be quite useful for folks wanting to run this inside docker containers.

**Comment by nbrownus** [comment]
The state of `auditd` and linux containers is a bit weird. You'd need to decide to run `go-audit` either in each container you have or on the host itself. A dedicated container running `go-audit` won't provide much value since it would only be monitoring its own container.
