### ISSUE TITLE
Pre-compiled version? 

### ISSUE THREAD

**Issue by Hack-Hut** [slackhq/go-audit#65]
Would like to move from auditd to go-audit, but the problem for me is that the machines that this will be installed on have no internet access. This means that the `govendor sync`  cannot resolve the dependencies `venor/vendor.json`. I'm not very familiar with go but know that it's compiled. If it's possible could you release a pre-compiled version? Cheers :)

**Comment by trixpan** [comment]
wouldn't it be better for you to compile and then sneaker copy the resulting binary to your internet disconnected nodes?

Also, without specifying what distro you are trying to build for, it is unlikely the issue will be addressed. ;-) 

Cheers

**Comment by Hack-Hut** [comment]
Yeah, I just compiled it at home. But the distro was Suse if you ever change your mind. :)

**Comment by nbrownus** [comment]
I'm not aware of any distro specific concerns but @trixpan has the right idea. Your best bet is to compile and ship in your preferred method (deb, rpm, tar, binary, etc). `go` makes this super simple.
