### ISSUE TITLE
wrong app name in syslogs

### ISSUE THREAD

**Issue by nbommu1** [slackhq/go-audit#68]
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

latest version has wrong app in syslogs.

#### Reproducible in:

`go-audit` version:
latest git clone
OS version(s):
amzn linux

#### Steps to reproduce:
when go audit is running I see host FQDN as app name 

### Expected result:
Aug 15 03:25:07 instance-test.abc.local  /usr/local/bin/go-audit[3262]
> e.g. What you expected to happen

### Actual result:
Aug 15 03:25:07 instance-test instance-test.abc.local /usr/local/bin/go-audit[3262]
> e.g. What actually happened

**Comment by nbrownus** [comment]
This can be set in [config](https://github.com/slackhq/go-audit/blob/master/go-audit.yaml.example#L58), if this isn't working for you, can you provide which syslog server and version you are using?
