### ISSUE TITLE
no tags/releases

### ISSUE THREAD

**Issue by jsleeio** [slackhq/go-audit#77]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/go-audit/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/go-audit/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

No releases/tags, and (per #65), no prebuilt binaries. I did notice that `make_deb.sh` includes a version `0.16.0`, but `contrib/go-audit.rpmbuild.spec` specifies version `1`.

I am trying to integrate `go-audit` into an AWS AMI build pipeline. At present I am cloning, checking out a specific commit, building a binary and copying it into my AMI volume. This works, but it's not particularly nice — which version have I installed? It also precludes semantic versioning.

With build tooling being very much a matter of taste and also org suitability I have not immediately created a PR. If a [Goreleaser](https://github.com/goreleaser/goreleaser) config would work for Slack I'll happily contribute one as I'm somewhat familiar with it via my own projects.

Thanks for sharing this software!

#### Reproducible in:

N/A

#### Steps to reproduce:

N/A

### Expected result:

Github releases, or at least version tags 

### Actual result:

No tags or releases

### Attachments:

N/A

**Comment by wadey** [comment]
Thanks for opening this, it is a great idea. We have a pretty good release process set up for the security team's other big project, Nebula. So I'll see if we can crib from that and get a good release set up over here as well.

**Comment by wadey** [comment]
v1.0.0 has been tagged and released with amd64 binaries :tada: https://github.com/slackhq/go-audit/releases/tag/v1.0.0

**Comment by jsleeio** [comment]
Thankyou, this is great!
