### ISSUE TITLE
go-audit relies on github.com/capsule8/capsule8, which was deleted or made private

### ISSUE THREAD

**Issue by mcpherrinm** [slackhq/go-audit#78]
I was discussing go-audit and looking at the code, and noticed I couldn't check out one of the dependencies.
I do see it on archive.org wayback machine, but I guess that project is dead.

https://github.com/capsule8/capsule8 404s

https://github.com/slackhq/go-audit/blob/42f8f9607bda947e55cb1aa7e2bce64c7208fd72/go.mod#L8

https://github.com/slackhq/go-audit/search?q=capsule8

Just an FYI that you might want to consider migrating off it.

**Comment by wadey** [comment]
Wow, that is strange! I have a local branch somewhere that I implemented this functionality myself before deciding to depend on capsule8. I can revive that code.

I also made a request to see if this is a temporary issue or if it was pulled permanently: https://twitter.com/wadey/status/1272667332519870465
